libexec: simplify

diff --git a/libexec/af-arch b/libexec/af-arch
--- a/libexec/af-arch
+++ b/libexec/af-arch
@@ -2,52 +2,34 @@
 # SPDX-License-Identifier: GPL-2.0-only
 # Copyright (c) 2019 Max Rees
 # See LICENSE for more information.
-scriptdir="${0%/*}"
-. "$scriptdir/common"
-required_commands join mktemp
 
-usage() {
-	printf 'Usage: %s [-q] [-b BRANCH] REPO/PKG ...\n' "$PROG" >&2
-}
-
-cleanup() {
-	rm -f "$tmp"
-}
-
-while getopts b:qh opt; do
-case "$opt" in
-b)
-	branch="$OPTARG";;
-q)
-	QUIET=1;;
-*)
-	usage
-	[ "$opt" = "h" ] && exit 0
-	exit 1
-esac
-done
-shift $((OPTIND - 1))
-
-if [ -z "$branch" ]; then
-	branch="$(get_branch)"
-fi
+# af-arch BRANCH STARTDIR [STARTDIR...]
+branch="$1"
+shift
+[ -n "$branch" ] || exit 1
 
 for startdir; do
 	any=0
 	repo="${startdir%/*}"
 
 	APKBUILD="$startdir/APKBUILD"
-	[ -e "$APKBUILD" ] || fatal 1 missing APKBUILD: "$APKBUILD"
+	if ! [ -e "$APKBUILD" ]; then
+		printf 'af-arch: %s: not found\n' "$APKBUILD" >&2
+		exit 2
+	fi
 
 	archfile=".apkfoundry/$branch/arch"
-	[ -e "$archfile" ] || fatal 1 missing configuration: "$archfile"
+	if ! [ -e "$archfile" ]; then
+		printf 'af-arch: %s: not found\n' "$archfile" >&2
+		exit 2
+	fi
 
 	arch="$(grep '^arch=' "$APKBUILD" \
 		| sed "s/^arch=//; s/'//g; s/\"//g; s/#.*\$//")"
 
 	want_arches="$(grep "^$repo " "$archfile" | cut -d ' ' -f 2-)"
 	if [ -z "$want_arches" ]; then
-		notice warning: repository "'$repo'" is not enabled
+		printf 'af-arch: warning: %s: repository not enabled\n' "$repo" >&2
 		continue
 	fi
 
@@ -71,6 +53,6 @@ for startdir; do
 		fi
 	done
 	if [ "$any" -eq 0 ]; then
-		notice warning: "$startdir" is disabled on all architectures
+		printf 'af-arch: warning: %s: not enabled on any arch\n' "$startdir" >&2
 	fi
 done
diff --git a/libexec/af-changes b/libexec/af-changes
--- a/libexec/af-changes
+++ b/libexec/af-changes
@@ -2,37 +2,21 @@
 # SPDX-License-Identifier: GPL-2.0-only
 # Copyright (c) 2018 Max Rees
 # See LICENSE for more information.
-scriptdir="${0%/*}"
-. "$scriptdir/common"
-required_commands git
 
-usage() {
-	printf 'Usage: %s [-q] -p BRANCH BEFORE AFTER\n' "${0##*/}" >&2
-	printf '       %s [-q] -m TARGET COMMITISH\n' "${0##*/}" >&2
-}
-
-while getopts p:mqh opt; do
+# af-changes -p BRANCH BEFORE AFTER
+# af-changes -m TARGET COMMITISH
+while getopts p:mq opt; do
 case "$opt" in
-p)
-	branch="$OPTARG";;
-m)
-  mr=1;;
-q)
-	QUIET=1;;
-*)
-	usage
-	[ "$opt" = "h" ] && exit 0
-	exit 1;;
+p) branch="$OPTARG";;
+m) mr=1;;
 esac
 done
-shift $((OPTIND - 1))
+shift "$((OPTIND - 1))"
 
 if [ -z "$branch" ] && [ -z "$mr" ]; then
-	usage
 	exit 1
 fi
 if [ -n "$branch" ] && [ -n "$mr" ]; then
-	usage
 	exit 1
 fi
 if [ -n "$mr" ]; then
@@ -42,7 +26,6 @@ fi
 before="$1"
 after="$2"
 if [ -z "$before" ] || [ -z "$after" ]; then
-	usage
 	exit 1
 fi
 
@@ -56,19 +39,23 @@ projectdir="${PWD##*/}"
 if [ -n "$mr" ]; then
 	base="$(git merge-base "$before" "$after")"
 	if [ -z "$base" ]; then
-		fatal 4 failed merge base: "$projectdir" "$before" "$after"
+		printf 'af-changes: failed merge base: %s %s %s\n' \
+			"$projectdir" "$before" "$after" >&2
+		exit 2
 	else
-		notice merge base: "$projectdir" "$before" "$after"
+		printf 'af-changes: %s %s %s\n' \
+			"$projectdir" "$before" "$after" >&2
 	fi
 	before="$base"
 fi
 
-notice changed packages: "$projectdir" "$before" "$after"
+printf 'af-changes: changed packages: %s %s %s\n' \
+	"$projectdir" "$before" "$after" >&2
 
 changes="$(git diff-tree -r --name-only --diff-filter dxu "$before..$after")"
 printf '%s' "$changes" \
 	| grep 'APKBUILD$' | sed 's#/APKBUILD$##' \
 	| while read -r pkg; do
-		notice package: "$pkg"
+		printf 'af-changes: %s\n' "$pkg" >&2
 		printf '%s\n' "$pkg"
 	done
